# version: '3.9'

services:
  db:
    image: postgres:14.2-alpine
    container_name: demo-postgres-14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "max_connections=500" ]
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  redis:
    image: redis:7.4-alpine
    container_name: demo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  demo-web:
    build: .
    restart: always
    container_name: demo-web
    command: ./bin/rails server -b 0.0.0.0
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - app-storage:/rails/storage
      - node_modules:/rails/node_modules
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
      # - "3001:3001"

volumes:
  postgres_data: {}
  app-storage: {}
  redis_data: {}
  node_modules: {}
